name: 远程请求构建

on:
  repository_dispatch:
    types:
      - windowsbuild

jobs:
  BuildForWin:
    runs-on: windows-latest

    steps:
      - name: checkout-main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: install-nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
          registry-url: 'https://registry.npmmirror.com/'
      - name: install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1
      - name: pnpm install
        run: |
          pnpm install
      - name: change website and name
        run: |
          sed  -i '' 's#VUE_APP_SITE=#VUE_APP_SITE=${{ github.event.client_payload.url }}#g' './.env'
          sed  -i '' 's#VUE_APP_NAME=#VUE_APP_NAME=${{ github.event.client_payload.name }}#g' './.env'
          sed  -i '' 's#VUE_APP_ID=#VUE_APP_ID=${{ github.event.client_payload.appid }}#g' './.env'
      - name: build-windows
        run: |
          pnpm run electron:build
      # - name: RAR
      #   run: |
      #     Compress-Archive -CompressionLevel Optimal -Force -Path ./dist_electron/*.exe -DestinationPath ${{ github.event.client_payload.name }}.zip
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.qq.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.EMAILUSERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.EMAILPASSWORD1}}
          # Required mail subject:
          subject: 你的应用已打包完成
          # Required recipients' addresses:
          to: ${{ github.event.client_payload.mail }}
          # Required sender full name (address can be skipped):
          from: Xing.Wu # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: 您好，您的应用已经打包成功，前往github查看构建记录，如有其他需求可回复本邮件
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional attachments:
          # attachments: ${{ github.event.client_payload.name }}.zip
      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.client_payload.name }}
          path: |
            ./.env
            ./dist_electron/*.exe
